### ISSUE TITLE
Crash on evb replay - Missing region

### ISSUE THREAD

**Issue by TastefulElk** [ljacobsson/evb-cli#11]
Heyo! 👋  I get an `UnhandledPromiseRejectionWarning` when trying to run `evb replay`. 

Content of `~/.aws/config`

```
[default]
region=eu-north-1
output=json
```
and I've got valid credentials for an IAM User in `~/.aws/credentials`.

The error I'm getting:
```
> evb replay
(node:2765) UnhandledPromiseRejectionWarning: ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/event_listeners.js:94:47)
    at Request.callListeners (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/config.js:386:7)
    at /usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/config.js:404:9
    at SharedIniFileCredentials.get (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/config.js:398:24)
    at Config.getCredentials (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/config.js:418:9)
    at Request.VALIDATE_CREDENTIALS (/usr/local/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/event_listeners.js:81:26)
(node:2765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Let me know if there's any other info you need!

**Comment by ljacobsson** [comment]
Thanks for reporting!

As a workaround, please set the `AWS_REGION` environment variable to your region.

I will release a proper fix asap :+1:
