### ISSUE TITLE
What privileges are required to use evb?

### ISSUE THREAD

**Issue by jvijay-work** [ljacobsson/evb-cli#40]
```
$ evb pattern
Could not find template.yaml. Will write pattern to stdout. Use -t <path to CloudFormation template to write to template>
/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/protocol/json.js:52
  resp.error = util.error(new Error(), error);
                          ^

MethodNotAllowed: User: arn:aws:sts::12345678901023:assumed-role/developer-admin/johnb is not authorized to perform: schemas:ListRegistries on resource: arn:aws:schemas:us-east-1:12345678901023:* with an explicit deny
    at Object.extractError (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/johnb/.nvm/versions/node/v16.13.0/lib/node_modules/@mhlabs/evb-cli/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'MethodNotAllowed',
  time: 2022-03-04T21:37:23.178Z,
  requestId: 'e3bdbd81-9f11-4a2d-b4f9-41d36b857a03',
  statusCode: 403,
  retryable: false,
  retryDelay: 80.26074495834715
```

**Comment by ljacobsson** [comment]
Hi, sorry for the late reply.

For the `pattern` command, you'll need `schemas:List*` and probably `schemas:Get*`. No write-actions are needed.
